/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAdd: typeof import('~icons/carbon/add')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
